apiVersion: v1
kind: ConfigMap
metadata:
  name: ci-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.configData "context" $) | nindent 2}}
  CACHE_CONFIG_REDIS_SENTINELS: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  CACHE_CONFIG_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  CACHE_CONFIG_REDIS_URL: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  ENABLE_AUTH: {{ .Values.enableAuth | quote }}
  GRPC_SERVER_PORT: {{.Values.service.grpcport | quote}}
  ADDON_IMAGE: '{{ .Values.ci_images.addon.image.repository }}:{{ .Values.ci_images.addon.image.tag }}'
  LE_IMAGE: '{{ .Values.ci_images.lite_engine.image.repository }}:{{ .Values.ci_images.lite_engine.image.tag }}'
  GIT_CLONE_IMAGE: '{{ .Values.ci_images.git_clone.image.repository }}:{{ .Values.ci_images.git_clone.image.tag }}'
  DOCKER_PUSH_IMAGE: '{{ .Values.ci_images.kaniko.image.repository }}:{{ .Values.ci_images.kaniko.image.tag }}'
  ECR_PUSH_IMAGE: '{{ .Values.ci_images.kaniko_ecr.image.repository }}:{{ .Values.ci_images.kaniko_ecr.image.tag }}'
  GCR_PUSH_IMAGE: '{{ .Values.ci_images.kaniko_gcr.image.repository }}:{{ .Values.ci_images.kaniko_gcr.image.tag }}'
  ACR_PUSH_IMAGE: '{{ .Values.ci_images.kaniko_acr.image.repository }}:{{ .Values.ci_images.kaniko_acr.image.tag }}'
  GCS_UPLOAD_IMAGE: '{{ .Values.ci_images.gcs_upload.image.repository }}:{{ .Values.ci_images.gcs_upload.image.tag }}'
  S3_UPLOAD_IMAGE: '{{ .Values.ci_images.s3_upload.image.repository }}:{{ .Values.ci_images.s3_upload.image.tag }}'
  ARTIFACTORY_UPLOAD_IMAGE: '{{ .Values.ci_images.artifactory_upload.image.repository }}:{{ .Values.ci_images.artifactory_upload.image.tag }}'
  GCS_CACHE_IMAGE: '{{ .Values.ci_images.gcs_cache.image.repository }}:{{ .Values.ci_images.gcs_cache.image.tag }}'
  S3_CACHE_IMAGE: '{{ .Values.ci_images.s3_cache.image.repository }}:{{ .Values.ci_images.s3_cache.image.tag }}'
  SECURITY_IMAGE: '{{ .Values.securityImage.image.repository }}:{{ .Values.securityImage.image.tag }}'
  LOGGING_LEVEL: {{ .Values.appLogLevel }}
  EVENTS_FRAMEWORK_REDIS_URL: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  EVENTS_FRAMEWORK_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  EVENTS_FRAMEWORK_REDIS_SENTINELS: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  LOCK_CONFIG_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  LOCK_CONFIG_REDIS_SENTINELS: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  LOCK_CONFIG_REDIS_URL: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  MEMORY: {{ .Values.java.memory | quote }}
 {{- if .Values.global.airgap }}
 {{- end }}
  NG_MANAGER_URL: 'http://ng-manager.{{ .Release.Namespace }}.svc.cluster.local:7090/'
  LOG_SERVICE_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/log-service/'
  TI_SERVICE_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/ti-service/'
  API_URL: '{{ .Values.global.loadbalancerURL }}/ng/#/'
  STO_SERVICE_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/sto/'
  {{- if .Values.global.ssca.enabled }}
  SSCA_SERVICE_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/ssca-manager/'
  SSCA_ORCHESTRATION_IMAGE: '{{ .Values.ci_images.ssca_plugin.image.repository }}:{{ .Values.ci_images.ssca_plugin.image.tag }}'
  SSCA_ENFORCEMENT_IMAGE: '{{ .Values.ci_images.ssca_plugin.image.repository }}:{{ .Values.ci_images.ssca_plugin.image.tag }}'
  VM_SSCA_ORCHESTRATION_IMAGE: '{{ .Values.ci_images.ssca_plugin.image.repository }}:{{ .Values.ci_images.ssca_plugin.image.tag }}'
  VM_SSCA_ENFORCEMENT_IMAGE: '{{ .Values.ci_images.ssca_plugin.image.repository }}:{{ .Values.ci_images.ssca_plugin.image.tag }}'
  SLSA_VERIFICATION_DOCKER_IMAGE: '{{ .Values.ci_images.slsa_plugin.image.repository }}:{{ .Values.ci_images.slsa_plugin.image.tag }}'
  SLSA_VERIFICATION_GCR_IMAGE: '{{ .Values.ci_images.slsa_plugin.image.repository }}:{{ .Values.ci_images.slsa_plugin.image.tag }}'
  DOCKER_PROVENANCE_IMAGE: '{{ .Values.ci_images.slsa_plugin.image.repository }}:{{ .Values.ci_images.slsa_plugin.image.tag }}'
  GCR_PROVENANCE_IMAGE: '{{ .Values.ci_images.slsa_plugin.image.repository }}:{{ .Values.ci_images.slsa_plugin.image.tag }}'
  {{- end }}
  STACK_DRIVER_LOGGING_ENABLED: {{ .Values.global.stackDriverLoggingEnabled | quote }}

  # The following image variables are just for the reference and do not impact any functionality
  HARNESS_CODE_GIT_URL: '{{ .Values.global.loadbalancerURL }}/code/git'
  {{ include "harnesscommon.harnessfunctions.java17flags" (dict "context" $) | nindent 2 }}
{{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
{{- end }}
